// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_-TPMXt0B-3FW6xbC96WdiWP91ty25uk',
    appId: '1:593075386775:web:55d85ff862e9795ac2ecd2',
    messagingSenderId: '593075386775',
    projectId: 'hz-360fa',
    authDomain: 'hz-360fa.firebaseapp.com',
    storageBucket: 'hz-360fa.appspot.com',
    measurementId: 'G-T6D0ND24D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtNER8-EqZN9-o-h9eu5H7ibG-4OdSxkY',
    appId: '1:593075386775:android:7e439b9d03cd0c87c2ecd2',
    messagingSenderId: '593075386775',
    projectId: 'hz-360fa',
    storageBucket: 'hz-360fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdKonjIt7HUqTvJMBP6ADA9bDcy_jYcLA',
    appId: '1:593075386775:ios:da3ed5b43c90f477c2ecd2',
    messagingSenderId: '593075386775',
    projectId: 'hz-360fa',
    storageBucket: 'hz-360fa.appspot.com',
    androidClientId: '593075386775-nb8e64fbqn02fnth87k5gf43765etr5j.apps.googleusercontent.com',
    iosClientId: '593075386775-fk2d5veh3j06lm7ahhe3vvea20t7mqth.apps.googleusercontent.com',
    iosBundleId: 'com.soda.app55hz',
  );
}
